Upgrade to recent version of nio4r
The previous version of nio4r failed to compile on macOS:

```
compiling selector.c
selector.c:301:26: error: incompatible function pointer types passing 'VALUE (*)(VALUE *)' (aka 'unsigned long (*)(unsigned long *)') to parameter of type 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned
long)') [-Wincompatible-function-pointer-types]
  301 |         return rb_ensure(func, (VALUE)args, NIO_Selector_unlock, self);
      |                          ^~~~
/Users/tkuah/.rbenv/versions/3.3.8/include/ruby-3.3.0/ruby/internal/iterator.h:425:25: note: passing argument to parameter 'b_proc' here
  425 | VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE data2);
      |                         ^
1 error generated.
make: *** [selector.o] Error 1

make failed, exit code 2
```

Since fixed by https://github.com/socketry/nio4r/issues/298.