Fix ActionView::Template::Error: undefined method `xpath'
Contributes to https://gitlab.com/gitlab-org/gitlab/-/issues/505231

**Problem**

Method `.render` returns `Gitlab::ErrorTracking.track_exception` result
in case of timeout error. It breaks further processing.

**Solution**

Return the original input in case of the timeout.

Changelog: fixed