fix: Double-check locking pattern
This commit fixes the error:

```shell
Caused by:
ThreadError: deadlock; recursive locking
/Users/hercules/GitLab/gdk/gitlab/lib/gitlab/metrics/prometheus.rb:97:in `synchronize'
/Users/hercules/GitLab/gdk/gitlab/lib/gitlab/metrics/prometheus.rb:97:in `safe_provide_metric'
/Users/hercules/GitLab/gdk/gitlab/lib/gitlab/metrics/prometheus.rb:63:in `counter'
/Users/hercules/GitLab/gdk/gitlab/lib/gitlab/instrumentation/redis_base.rb:124:in `instance_count_request'
/Users/hercules/GitLab/gdk/gitlab/lib/gitlab/instrumentation/redis_helper.rb:10:in `instrument_call'
/Users/hercules/GitLab/gdk/gitlab/lib/gitlab/instrumentation/redis_client_middleware.rb:13:in `call'
/Users/hercules/GitLab/gdk/gitlab/lib/gitlab/patch/redis_client.rb:12:in `ensure_connected'
/Users/hercules/GitLab/gdk/gitlab/lib/feature.rb:325:in `block in current_feature_value'
...
```

1. safe_provide_metric acquires PROVIDER_MUTEX.synchronize
2. It calls provide_metric(metric_type, metric_name, *args)
3. registry.get(metric_name) returns nil (metric doesn't exist)
4. The || operator triggers registry.method(metric_type).call(metric_name, *args)
5. The registry call goes through Redis instrumentation, triggered by Gitlab::CurrentSettings.prometheus_metrics_enabled
6. The instrumentation tries to record its own metrics, calling safe_provide_metric again, which tries to acquire the same mutex that's already held

This issue was only present in Gitlab::Metrics::Prometheus. The
Gitlab::Metrics::Labkit implementation is not affected by that.

This bug has been introduced due to an attempt of simplifying the
current implementation, as a step to replace it by Labkit::Metrics,
however, this edge case of recursive call wasn't clear given the hidden
call to the metrics library from a instrumentation object call within a
method call from the model.