Fix missing :: in prepended modules
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/183342 added
calls to `Gitlab.com?`, but this might not be resolved properly in a
prepended EE module.  In
https://gitlab.com/gitlab-org/gitlab/-/jobs/9322115549, I see:

```
     NoMethodError:
       undefined method `com?' for module EE::Gitlab
```