GitHub import handle requested_reviewer nil
We can see some errors in Sentry:

```
NoMethodError
undefined method `login' for nil:NilClass (NoMethodError)

              "`@#{issue_event[:requested_reviewer].login}`"
                                                   ^^^^^^
```

Sometimes the GitHub API can return back `nil` users, most likely
because they are deleted or banned.

In this case, replace the missing username with `@ghost`.

https://new-sentry.gitlab.net/organizations/gitlab/issues/1227347

Changelog: fixed