Scrub non-UTF characters from context chunk
This MR removes non-UTF characters from the logged context chunks. This
is because the context chunk is passed to `Gitlab::Json.dump`, which
raises an exception if it receives a non-printable character:

> Gitlab::Json.dump(chunk: "hello\x8d")

EncodingError: Invalid Unicode [8d] at 5

> Gitlab::Json.dump(chunk: "hello\x8d".scrub)

"{\"chunk\":\"hello�\"}"

Changelog: fixed