Fix NoMethodError for Projects::BlobController#diff_lines
Sentry error:
https://new-sentry.gitlab.net/organizations/gitlab/issues/1794354

**Problem**

```
NoMethodError: undefined method `empty?' for
nil:NilClass (NoMethodError)

    return render_404 if diff_hunks.empty?
```

`ViewerHunk#init_from_expanded_lines` returns `nil` instead of `[]`.

**Solution**

Return `[]` to match expectation and resolve the error.

Changelog: fixed