Fix TypeError when JSON table contains array instead of hash
**Problem**

Sentry error: https://new-sentry.gitlab.net/organizations/gitlab/issues/1815052

```
TypeError: no implicit conversion of String into Integer (TypeError)

        return unless json['markdown']
                           ^^^^^^^^^^
  from lib/banzai/filter/json_table_filter.rb:47:in `process_json_table'
  from lib/banzai/filter/json_table_filter.rb:26:in `block in call'
```

**Solution**

Check that parsed JSON is a Hash before accessing string keys
to prevent TypeError when JSON contains an array.

Changelog: fixed