Make migration handle loss of ci_runners_e59bb2812d table
GDK users have been seeing this error:

```
main: == 20250304231245 IncreaseTokenEncryptedConstraint: migrating =================
main: -- transaction_open?(nil)
main:    -> 0.0000s
main: -- transaction_open?(nil)
main:    -> 0.0000s
main: -- execute("ALTER TABLE ci_runners_e59bb2812d\nADD CONSTRAINT check_030ad0773d\nCHECK ( char_length(token_encrypted) <= 512 )\nNOT VALID;\n")
main: == [advisory_lock_connection] object_id: 132620, pg_backend_pid: 37123
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "ci_runners_e59bb2812d" does not exist
```

This happened because:

1. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/182549
renamed the `ci_runners_e59bb2812d` table to `ci_runners`.
2. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/183389
reverted that change.

This leaves some database schemas in a state where
`ci_runners_e59bb2812d` no longer exists.

This commit adjusts the migration in
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/183454 to fall
back to the `ci_runners` table if `ci_runners_e59bb2812d` no longer
exists.