Check for nil in ValidateTokenService#expired_token?
`expired_token?` assumes that `:unlock_token` or `:confirmation_token`
is present. If it isn't, `NoMethodError: undefined method `<' for nil`
is raised.

This change adds a nil check so that `true` is returned ("Yes, it is an
expired token"), instead of an error.