Fixed vue/no-unused-properties eslint errors:
Exception: Referenced in parent     38:5  error  'noAccessSvgPath' of property found, but never used                 vue/no-unused-properties
Removed                             70:5  error  'displayStageEvents' of computed property found, but never used     vue/no-unused-properties
Removed                             74:5  error  'displayNotEnoughData' of computed property found, but never used   vue/no-unused-properties
Removed                             134:7  error  'fetchStageData' of method found, but never used                   vue/no-unused-properties
Removed                             150:5  error  'dismissOverviewDialog' of method found, but never used            vue/no-unused-properties