Fix NoMethodError from Projects::CompareController#show
Sentry error:
https://new-sentry.gitlab.net/organizations/gitlab/issues/1790363

**Problem**

```
NoMethodError: undefined method `diff_refs' for
nil:NilClass (NoMethodError)

        send_git_diff source_project.repository, compare.diff_refs
                                                        ^^^^^^^^^^
```

The validation for presence of compare results is missing for patch and
diff formats.

**Solution**

Return 404 error when compare results are not available.

Changelog: fixed