Drop Rails dependency
This dependency clashes with code which does not use Rails but tries to
mimic it (fast_spec_helper).

The Rails dependency is replaced by checking RAILS_ENV variable
verbatim.

This fixes the following error:

  Failure/Error: require_relative '../config/initializers_before_autoloader/004_zeitwerk'

  NoMethodError:
    undefined method `autoloaders' for nil
  # ./config/initializers_before_autoloader/004_zeitwerk.rb:3:in `<top (required)>'
  # ./spec/rails_autoload.rb:49:in `require_relative'
  # ./spec/rails_autoload.rb:49:in `<top (required)>'
  # ./spec/fast_spec_helper.rb:27:in `require_relative'