test: Refactor test utility configure_mock_auth
The login helper allows passing the parameter `additional_info`
that is intended to be merged with the other OAuth ID token claims.

Unfortunately, this is not working because the following error
is raised when passing additional info:

```console
NoMethodError:
  undefined method `merge' for #<OneLogin::RubySaml::Attributes>
```

EE: true

Changelog: other